name: NovaTV
options:
  bundleIdPrefix: net.digitalnoise
  deploymentTarget:
    tvOS: "17.0"
  xcodeVersion: "16.0"
settings:
  base:
    DEVELOPMENT_TEAM: QRRCB8HB3W
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
targets:
  NovaTV:
    type: application
    platform: tvOS
    sources:
      - path: NovaTV
        excludes:
          - "Assets.xcassets"
    settings:
      base:
        INFOPLIST_FILE: NovaTV/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: net.digitalnoise.NovaTV
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
  NovaTVTests:
    type: bundle.unit-test
    platform: tvOS
    sources:
      - path: NovaTVTests
    dependencies:
      - target: NovaTV
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: net.digitalnoise.NovaTVTests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/NovaTV.app/NovaTV"
        BUNDLE_LOADER: "$(TEST_HOST)"
        GENERATE_INFOPLIST_FILE: "YES"
